# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- trunk

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- task: PythonScript@0
  inputs:
    scriptPath: ./ci/azure-report-env.py
  displayName: 'Build environment details'

- task: PythonScript@0
  inputs:
    scriptPath: ./ci/azure-install-deps.py
  displayName: 'Install dependencies'

# doc/ contains stuff that is currently exempt from linting
- script: |
    exec flake8 $(git ls-files '*.py' | grep -v '^doc/')
  displayName: 'Lint cyexiv2'

- task: PythonScript@0
  inputs:
    scriptPath: ./ci/azure-build-libexiv2.py
  displayName: 'Build libexiv2'

- task: PythonScript@0
  inputs:
    scriptPath: ./ci/azure-build-cyexiv2.py
  displayName: 'Build cyexiv2'

- script: |
    exec pytest tests --doctest-modules --junitxml=junit/test-results.xml \
                      --cov=com --cov-report=xml --cov-report=html
  displayName: 'Test cyexiv2'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Test results for Python $(python.version)'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
